// SYNTH — Nemesis System
// Named elite enemies that persist across runs via localStorage.
// Inspired by Shadow of Mordor: enemies that kill you come back stronger.
// Generated by kbot (local Qwen 32B, $0) + refined by Claude Code.

import type { EnemyType } from '../types'

interface Nemesis {
  id: string
  name: string
  title: string
  enemyType: EnemyType
  killCount: number
  scars: string[]
  taunt: string
  hpMultiplier: number
  damageMultiplier: number
  speedMultiplier: number
  createdAt: number
}

const STORAGE_KEY = 'synth_nemeses'
const MAX_NEMESES = 5

const NAMES = [
  'Arakyn', 'Thalorin', 'Xenara', 'Grimlock', 'Zephyr',
  'Nyxara', 'Drakeon', 'Morgath', 'Nocturne', 'Vespera',
  'Tyrannor', 'Kethis', 'Solvex', 'Ashkari', 'Vrenn',
  'Malchor', 'Qirin', 'Zerith', 'Obsidra', 'Tormund',
  'Halvex', 'Skarn', 'Fael', 'Cindra', 'Revex',
  'Ghol', 'Pyros', 'Nethis', 'Umbral', 'Krexx',
]

const TITLES = [
  'the Unyielding', 'of the Abyss', 'Bane of Light',
  'the Relentless', 'Voidtouched', 'the Scarred',
  'Ironhide', 'Deathbringer', 'the Hungry',
  'Flamewraith', 'the Patient', 'Shadowborn',
  'the Merciless', 'Corruptor', 'the Undying',
]

const SCARS = [
  'a jagged scar across its core',
  'one eye socket dark and hollow',
  'melted plating along its flank',
  'cracks spidering through its shell',
  'a missing limb, replaced with raw energy',
  'burn marks from your last encounter',
  'a dent where your finishing blow landed',
  'electrical sparks from damaged circuits',
  'a chunk torn from its shield',
  'glowing wounds that never healed',
]

const TAUNTS = [
  'Remember me?',
  'You left me for dead. Mistake.',
  'This time, you stay down.',
  'I learned from last time.',
  'Your partner can\'t save you.',
  'I\'ve been waiting.',
  'Every scar you gave me made me stronger.',
  'The dungeon remembers.',
  'Again? I thought you\'d learned.',
  'I carried your defeat with me.',
  'No retreat this time.',
  'You should have finished me.',
  'I know your patterns now.',
  'The Core sent me back for you.',
  'This ends differently.',
  'Pain is a teacher. I graduated.',
  'Run. It won\'t help.',
  'Your tricks won\'t work twice.',
  'I dreamed of this moment.',
  'Last time was practice.',
]

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

class NemesisSystem {
  private nemeses: Nemesis[] = []

  constructor() {
    this.load()
  }

  /** Create a new nemesis from the enemy that killed the player */
  createFromKill(enemyType: EnemyType): Nemesis {
    const nem: Nemesis = {
      id: Math.random().toString(36).slice(2, 11),
      name: pick(NAMES),
      title: pick(TITLES),
      enemyType,
      killCount: 1,
      scars: [],
      taunt: pick(TAUNTS),
      hpMultiplier: 1.3,
      damageMultiplier: 1.2,
      speedMultiplier: 1.1,
      createdAt: Date.now(),
    }

    this.nemeses.push(nem)

    // Trim to max — remove oldest
    if (this.nemeses.length > MAX_NEMESES) {
      this.nemeses.sort((a, b) => b.createdAt - a.createdAt)
      this.nemeses = this.nemeses.slice(0, MAX_NEMESES)
    }

    this.save()
    return nem
  }

  /** Promote a nemesis that killed the player again — gets scarier */
  promote(id: string): void {
    const nem = this.nemeses.find(n => n.id === id)
    if (!nem) return

    nem.killCount++
    nem.scars.push(pick(SCARS))
    nem.taunt = pick(TAUNTS)
    nem.hpMultiplier *= 1.2
    nem.damageMultiplier *= 1.15
    nem.speedMultiplier *= 1.05

    this.save()
  }

  /** Remove a nemesis that the player finally defeated */
  defeat(id: string): void {
    this.nemeses = this.nemeses.filter(n => n.id !== id)
    this.save()
  }

  /** Get nemeses to spawn in the current run (1-2 per floor) */
  getForRun(floorNumber: number): Nemesis[] {
    if (this.nemeses.length === 0) return []
    // Higher floors may face more nemeses
    const count = Math.min(1 + Math.floor(floorNumber / 3), this.nemeses.length, 2)
    // Pick the most dangerous ones (highest kill count)
    const sorted = [...this.nemeses].sort((a, b) => b.killCount - a.killCount)
    return sorted.slice(0, count)
  }

  /** Get display string for a nemesis */
  getDisplayName(nem: Nemesis): string {
    return `${nem.name} ${nem.title}`
  }

  /** Get all nemeses (for debug/display) */
  getAll(): Readonly<Nemesis[]> {
    return this.nemeses
  }

  private save(): void {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.nemeses))
    } catch { /* silent */ }
  }

  private load(): void {
    try {
      const raw = localStorage.getItem(STORAGE_KEY)
      if (raw) {
        this.nemeses = JSON.parse(raw) as Nemesis[]
      }
    } catch {
      this.nemeses = []
    }
  }
}

export const nemesisSystem = new NemesisSystem()
export type { Nemesis }
