import os
import sys
from admin.engineers.broadcaster import Broadcaster

def verify_tiktok():
    print("Verifying TikTok Automation...")
    
    broadcaster = Broadcaster()
    
    # 1. Test Video Generation
    print("\n[1/2] Testing Video Generation...")
    mock_post = {
        'title': 'Test TikTok Video',
        'content': 'This is a test video generated by the Broadcaster agent.'
    }
    
    video_path = broadcaster.generate_video(mock_post)
    
    if video_path and os.path.exists(video_path):
        print(f"✅ Video generated successfully: {video_path}")
    else:
        print("❌ Video generation failed.")
        return

    # 2. Test Upload (Optional)
    print("\n[2/2] Testing Upload...")
    if os.path.exists(broadcaster.cookies_path):
        print("✅ cookies.txt found.")
        response = input("Do you want to attempt an upload to TikTok? (y/n): ")
        if response.lower() == 'y':
            print("Attempting upload...")
            success = broadcaster.upload_to_tiktok(video_path, description="Test upload from Studio OS #test")
            if success:
                print("✅ Upload successful!")
            else:
                print("❌ Upload failed.")
        else:
            print("Skipping upload.")
    else:
        print("❌ cookies.txt NOT found.")
        print(f"Please save your TikTok cookies to: {broadcaster.cookies_path}")
        print("You can use a browser extension like 'Get cookies.txt LOCALLY' to export them.")

if __name__ == "__main__":
    verify_tiktok()
