// SYNTH — Upgrade / Progression System
// On level up, player picks 1 of 3 random upgrades.
// Generated by kbot (local Qwen 32B, $0) + refined by Claude Code.

export type UpgradeCategory = 'attack' | 'defense' | 'speed' | 'partner' | 'special'
export type UpgradeRarity = 'common' | 'rare' | 'epic'

export interface Upgrade {
  id: string
  name: string
  description: string
  category: UpgradeCategory
  rarity: UpgradeRarity
  stat: string
  value: number
}

export const UPGRADE_POOL: Upgrade[] = [
  // Attack
  { id: 'dmg_boost', name: 'Sharpened Core', description: '+15% damage', category: 'attack', rarity: 'common', stat: 'damage', value: 1.15 },
  { id: 'fire_rate', name: 'Overclock', description: '-20% attack cooldown', category: 'attack', rarity: 'common', stat: 'attackCooldown', value: 0.8 },
  { id: 'multi_shot', name: 'Split Beam', description: 'Fire 2 projectiles', category: 'attack', rarity: 'rare', stat: 'projectileCount', value: 2 },
  { id: 'crit_chance', name: 'Precision Matrix', description: '+10% crit chance', category: 'attack', rarity: 'rare', stat: 'critChance', value: 0.10 },
  { id: 'pierce', name: 'Penetrator', description: 'Shots pierce 1 enemy', category: 'attack', rarity: 'epic', stat: 'pierce', value: 1 },

  // Defense
  { id: 'max_hp', name: 'Reinforced Shell', description: '+25 max HP', category: 'defense', rarity: 'common', stat: 'maxHp', value: 25 },
  { id: 'armor', name: 'Plating', description: '-15% damage taken', category: 'defense', rarity: 'common', stat: 'damageReduction', value: 0.85 },
  { id: 'dodge_cd', name: 'Phase Shifter', description: '-200ms dodge cooldown', category: 'defense', rarity: 'rare', stat: 'dodgeCooldown', value: -200 },
  { id: 'iframes', name: 'Temporal Shield', description: '+100ms invincibility', category: 'defense', rarity: 'rare', stat: 'invincibilityMs', value: 100 },
  { id: 'shield_on_kill', name: 'Harvest Shield', description: 'Gain 10 HP on kill', category: 'defense', rarity: 'epic', stat: 'healOnKill', value: 10 },

  // Speed
  { id: 'move_speed', name: 'Thruster Boost', description: '+12% move speed', category: 'speed', rarity: 'common', stat: 'moveSpeed', value: 1.12 },
  { id: 'dash_range', name: 'Extended Dash', description: '+40% dash distance', category: 'speed', rarity: 'rare', stat: 'dashSpeed', value: 1.4 },
  { id: 'dash_cd', name: 'Quick Recovery', description: '-200ms dash cooldown', category: 'speed', rarity: 'rare', stat: 'dashCooldown', value: -200 },

  // Partner
  { id: 'partner_dmg', name: 'Synth Upgrade', description: '+20% partner damage', category: 'partner', rarity: 'common', stat: 'partnerDamage', value: 1.2 },
  { id: 'partner_hp', name: 'Synth Armor', description: '+30 partner max HP', category: 'partner', rarity: 'common', stat: 'partnerMaxHp', value: 30 },
  { id: 'partner_aggro', name: 'Tactical Override', description: 'Partner attacks more aggressively', category: 'partner', rarity: 'rare', stat: 'partnerAggression', value: 0.3 },
  { id: 'partner_heal', name: 'Repair Protocol', description: 'Partner heals 2 HP/s', category: 'partner', rarity: 'epic', stat: 'partnerRegen', value: 2 },

  // Special
  { id: 'lifesteal', name: 'Vampiric Core', description: 'Heal 5% of damage dealt', category: 'special', rarity: 'epic', stat: 'lifesteal', value: 0.05 },
  { id: 'explosive', name: 'Volatile Rounds', description: 'Shots explode on impact (32px AoE)', category: 'special', rarity: 'epic', stat: 'explosiveRadius', value: 32 },
  { id: 'chain', name: 'Arc Conductor', description: 'Hits chain to 2 nearby enemies', category: 'special', rarity: 'epic', stat: 'chainTargets', value: 2 },
  { id: 'freeze', name: 'Cryo Rounds', description: 'Shots slow enemies 50% for 1s', category: 'special', rarity: 'epic', stat: 'slowDuration', value: 1000 },
  { id: 'double_xp', name: 'Data Siphon', description: '2x XP from kills', category: 'special', rarity: 'rare', stat: 'xpMultiplier', value: 2 },
  { id: 'thorns', name: 'Reactive Plating', description: 'Reflect 20% damage to attackers', category: 'special', rarity: 'rare', stat: 'thorns', value: 0.2 },
  { id: 'berserker', name: 'Berserker Protocol', description: '+30% damage, -15% speed, below 30% HP', category: 'special', rarity: 'epic', stat: 'berserker', value: 1.3 },
  { id: 'magnet', name: 'Loot Magnet', description: 'Pickups pulled from 3x distance', category: 'special', rarity: 'common', stat: 'pickupRange', value: 3 },
]

/** XP required for a given level (exponential curve) */
export function xpForLevel(level: number): number {
  return Math.floor(50 * Math.pow(1.2, level - 1))
}

/** Roll 3 upgrade choices, weighted by rarity. Higher levels = more rare/epic. */
export function rollUpgradeChoices(level: number): Upgrade[] {
  // Rarity weights shift with level
  const epicWeight = Math.min(0.05 + level * 0.02, 0.25)
  const rareWeight = Math.min(0.2 + level * 0.01, 0.35)
  const commonWeight = 1 - epicWeight - rareWeight

  const choices: Upgrade[] = []
  const used = new Set<string>()

  while (choices.length < 3) {
    const roll = Math.random()
    const rarity: UpgradeRarity = roll < commonWeight ? 'common' : roll < commonWeight + rareWeight ? 'rare' : 'epic'
    const pool = UPGRADE_POOL.filter(u => u.rarity === rarity && !used.has(u.id))
    if (pool.length === 0) continue
    const pick = pool[Math.floor(Math.random() * pool.length)]
    choices.push(pick)
    used.add(pick.id)
  }

  return choices
}
