"""
Residue Protocol - Automated Conversation Compounding
Sovereign Laboratory OS - AI Engineering Infrastructure

This module handles the generation of 'cognitive residue'—structured artifacts 
that preserve the reasoning, decisions, and state of an agent interaction.
"""

import os
import json
from datetime import datetime
from typing import Dict, Any, Optional
from admin.config import config

class ResidueProtocol:
    @staticmethod
    def generate_residue(agent_id: str, mission_id: str, data: Dict[str, Any]) -> str:
        """
        Generates and saves a residue artifact.
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        residue_dir = os.path.join(config.BRAIN_DIR, 'missions', mission_id)
        os.makedirs(residue_dir, exist_ok=True)
        
        filepath = os.path.join(residue_dir, f"residue_{agent_id}_{timestamp}.md")
        
        content = f"""# Cognitive Residue: {agent_id.capitalize()}
**Timestamp**: {datetime.now().isoformat()}
**Mission ID**: {mission_id}

## Executive Summary
{data.get('summary', 'No summary provided.')}

## Key Decisions
{ResidueProtocol._format_list(data.get('decisions', []))}

## Hypotheses & Reflections
{data.get('reflections', 'No reflections recorded.')}

## Technical Artifacts
{ResidueProtocol._format_list(data.get('artifacts', []))}

---
*Generated by the Antigravity Residue Protocol*
"""
        with open(filepath, 'w') as f:
            f.write(content)
            
        return filepath

    @staticmethod
    def _format_list(items: list) -> str:
        if not items:
            return "None recorded."
        return "\n".join([f"- {item}" for item in items])

def save_residue(agent_id: str, data: Dict[str, Any], mission_id: Optional[str] = None) -> str:
    """Helper to save residue with automated mission tracking."""
    if not mission_id:
        mission_id = "general_research"
    return ResidueProtocol.generate_residue(agent_id, mission_id, data)
