{
	"patcher": {
		"fileversion": 1,
		"appversion": { "major": 9, "minor": 0, "revision": 0, "architecture": "x64", "modernui": 1 },
		"classnamespace": "box",
		"rect": [100, 100, 900, 700],
		"openinpresentation": 1,
		"default_fontsize": 12.0,
		"default_fontname": "Arial",
		"devicewidth": 300.0,
		"description": "kbot Drum Synth — pure M4L synthesis. Kick=sine+pitch env, Snare=noise+body, Hats=HP noise",
		"digest": "No samples. All drums synthesized from oscillators and noise.",
		"tags": "kbot drums synth synthesis kick snare hat 808",

		"boxes": [
			{ "box": { "id": "obj-midiin", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [30, 30, 60, 22], "text": "midiin" } },
			{ "box": { "id": "obj-midiparse", "maxclass": "newobj", "numinlets": 1, "numoutlets": 8, "outlettype": ["", "", "", "", "", "", "", ""], "patching_rect": [30, 60, 120, 22], "text": "midiparse" } },
			{ "box": { "id": "obj-stripnote", "maxclass": "newobj", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [30, 90, 80, 22], "text": "stripnote" } },
			{ "box": { "id": "obj-js", "maxclass": "newobj", "numinlets": 3, "numoutlets": 8, "outlettype": ["", "", "", "", "", "", "", ""], "patching_rect": [30, 140, 350, 22], "text": "js kbot-drum-synth.js" } },
			{ "box": { "id": "obj-genre-dial", "maxclass": "live.dial", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "float"], "patching_rect": [400, 30, 60, 52], "presentation": 1, "presentation_rect": [15, 45, 60, 52], "parameter_enable": 1, "saved_attribute_attributes": { "valueof": { "parameter_longname": "Genre", "parameter_shortname": "Genre", "parameter_type": 0, "parameter_mmin": 0.0, "parameter_mmax": 1.0, "parameter_initial_enable": 1, "parameter_initial": [0.0] } } } },

			{ "box": { "id": "obj-kick-amp-msg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [30, 200, 130, 22], "text": "1. 1, 0. 300" } },
			{ "box": { "id": "obj-kick-pitch-msg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [30, 230, 130, 22], "text": "200 1, 50 80" } },
			{ "box": { "id": "obj-kick-aenv", "maxclass": "newobj", "numinlets": 2, "numoutlets": 2, "outlettype": ["signal", "bang"], "patching_rect": [30, 260, 60, 22], "text": "line~" } },
			{ "box": { "id": "obj-kick-penv", "maxclass": "newobj", "numinlets": 2, "numoutlets": 2, "outlettype": ["signal", "bang"], "patching_rect": [180, 260, 60, 22], "text": "line~" } },
			{ "box": { "id": "obj-kick-osc", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [180, 290, 60, 22], "text": "cycle~" } },
			{ "box": { "id": "obj-kick-vel", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [100, 230, 50, 22], "text": "sig~" } },
			{ "box": { "id": "obj-kick-mul1", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [30, 320, 40, 22], "text": "*~" } },
			{ "box": { "id": "obj-kick-mul2", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [30, 350, 40, 22], "text": "*~" } },

			{ "box": { "id": "obj-snr-amp-msg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [300, 200, 130, 22], "text": "1. 1, 0. 150" } },
			{ "box": { "id": "obj-snr-aenv", "maxclass": "newobj", "numinlets": 2, "numoutlets": 2, "outlettype": ["signal", "bang"], "patching_rect": [300, 260, 60, 22], "text": "line~" } },
			{ "box": { "id": "obj-snr-noise", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [390, 260, 55, 22], "text": "noise~" } },
			{ "box": { "id": "obj-snr-bp", "maxclass": "newobj", "numinlets": 3, "numoutlets": 4, "outlettype": ["signal", "signal", "signal", "signal"], "patching_rect": [390, 290, 100, 22], "text": "svf~ 2500 1.5" } },
			{ "box": { "id": "obj-snr-body", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [500, 260, 70, 22], "text": "cycle~ 200" } },
			{ "box": { "id": "obj-snr-bodygain", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [500, 290, 55, 22], "text": "*~ 0.3" } },
			{ "box": { "id": "obj-snr-mix", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [390, 320, 40, 22], "text": "+~" } },
			{ "box": { "id": "obj-snr-mul", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [300, 320, 40, 22], "text": "*~" } },
			{ "box": { "id": "obj-snr-vel", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [350, 230, 50, 22], "text": "sig~" } },
			{ "box": { "id": "obj-snr-mul2", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [300, 350, 40, 22], "text": "*~" } },

			{ "box": { "id": "obj-hat-ch-msg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [580, 200, 120, 22], "text": "1. 1, 0. 40" } },
			{ "box": { "id": "obj-hat-oh-msg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [710, 200, 120, 22], "text": "1. 1, 0. 250" } },
			{ "box": { "id": "obj-hat-aenv", "maxclass": "newobj", "numinlets": 2, "numoutlets": 2, "outlettype": ["signal", "bang"], "patching_rect": [580, 260, 60, 22], "text": "line~" } },
			{ "box": { "id": "obj-hat-noise", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [660, 260, 55, 22], "text": "noise~" } },
			{ "box": { "id": "obj-hat-hp", "maxclass": "newobj", "numinlets": 3, "numoutlets": 4, "outlettype": ["signal", "signal", "signal", "signal"], "patching_rect": [660, 290, 100, 22], "text": "svf~ 8000 0.5" } },
			{ "box": { "id": "obj-hat-mul", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [580, 320, 40, 22], "text": "*~" } },
			{ "box": { "id": "obj-hat-vel", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [630, 230, 50, 22], "text": "sig~" } },
			{ "box": { "id": "obj-hat-mul2", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [580, 350, 40, 22], "text": "*~" } },
			{ "box": { "id": "obj-hat-sel", "maxclass": "newobj", "numinlets": 3, "numoutlets": 3, "outlettype": ["bang", "bang", ""], "patching_rect": [710, 170, 80, 22], "text": "sel 0 1" } },

			{ "box": { "id": "obj-mix1", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [30, 420, 40, 22], "text": "+~" } },
			{ "box": { "id": "obj-mix2", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [30, 450, 40, 22], "text": "+~" } },
			{ "box": { "id": "obj-master-gain", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [30, 480, 60, 22], "text": "*~ 0.7" } },
			{ "box": { "id": "obj-out", "maxclass": "newobj", "numinlets": 2, "numoutlets": 0, "patching_rect": [30, 520, 80, 22], "text": "plugout~ 2" } },

			{ "box": { "id": "obj-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [30, 580, 200, 20], "text": "kbot Drum Synth v1.0", "fontface": 1, "fontsize": 13, "presentation": 1, "presentation_rect": [15, 8, 200, 20] } },
			{ "box": { "id": "obj-sub", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [30, 600, 250, 18], "text": "Pure synthesis — no samples", "fontsize": 9, "textcolor": [0.5,0.5,0.5,1], "presentation": 1, "presentation_rect": [15, 27, 200, 14] } },
			{ "box": { "id": "obj-status", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [400, 140, 200, 20], "text": "Ready", "presentation": 1, "presentation_rect": [15, 105, 200, 18] } },
			{ "box": { "id": "obj-set-status", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [400, 170, 80, 22], "text": "prepend set" } }
		],

		"lines": [
			{ "patchline": { "source": ["obj-midiin", 0], "destination": ["obj-midiparse", 0] } },
			{ "patchline": { "source": ["obj-midiparse", 0], "destination": ["obj-stripnote", 0] } },
			{ "patchline": { "source": ["obj-midiparse", 1], "destination": ["obj-stripnote", 1] } },
			{ "patchline": { "source": ["obj-stripnote", 0], "destination": ["obj-js", 0] } },
			{ "patchline": { "source": ["obj-stripnote", 1], "destination": ["obj-js", 1] } },
			{ "patchline": { "source": ["obj-genre-dial", 1], "destination": ["obj-js", 2] } },

			{ "patchline": { "source": ["obj-js", 0], "destination": ["obj-kick-amp-msg", 0], "comment": "kick trigger → amp env" } },
			{ "patchline": { "source": ["obj-js", 0], "destination": ["obj-kick-pitch-msg", 0], "comment": "kick trigger → pitch env" } },
			{ "patchline": { "source": ["obj-js", 1], "destination": ["obj-kick-vel", 0], "comment": "kick vel → sig~" } },
			{ "patchline": { "source": ["obj-kick-amp-msg", 0], "destination": ["obj-kick-aenv", 0] } },
			{ "patchline": { "source": ["obj-kick-pitch-msg", 0], "destination": ["obj-kick-penv", 0] } },
			{ "patchline": { "source": ["obj-kick-penv", 0], "destination": ["obj-kick-osc", 0], "comment": "pitch env → cycle~ freq" } },
			{ "patchline": { "source": ["obj-kick-osc", 0], "destination": ["obj-kick-mul1", 0], "comment": "osc → * amp" } },
			{ "patchline": { "source": ["obj-kick-aenv", 0], "destination": ["obj-kick-mul1", 1], "comment": "amp env → *" } },
			{ "patchline": { "source": ["obj-kick-mul1", 0], "destination": ["obj-kick-mul2", 0], "comment": "kick × vel" } },
			{ "patchline": { "source": ["obj-kick-vel", 0], "destination": ["obj-kick-mul2", 1] } },

			{ "patchline": { "source": ["obj-js", 2], "destination": ["obj-snr-amp-msg", 0], "comment": "snare trigger" } },
			{ "patchline": { "source": ["obj-js", 3], "destination": ["obj-snr-vel", 0], "comment": "snare vel" } },
			{ "patchline": { "source": ["obj-snr-amp-msg", 0], "destination": ["obj-snr-aenv", 0] } },
			{ "patchline": { "source": ["obj-snr-noise", 0], "destination": ["obj-snr-bp", 0], "comment": "noise → BP filter" } },
			{ "patchline": { "source": ["obj-snr-bp", 2], "destination": ["obj-snr-mix", 0], "comment": "BP output → mix" } },
			{ "patchline": { "source": ["obj-snr-body", 0], "destination": ["obj-snr-bodygain", 0] } },
			{ "patchline": { "source": ["obj-snr-bodygain", 0], "destination": ["obj-snr-mix", 1], "comment": "body → mix" } },
			{ "patchline": { "source": ["obj-snr-mix", 0], "destination": ["obj-snr-mul", 1], "comment": "mixed noise+body" } },
			{ "patchline": { "source": ["obj-snr-aenv", 0], "destination": ["obj-snr-mul", 0], "comment": "amp env" } },
			{ "patchline": { "source": ["obj-snr-mul", 0], "destination": ["obj-snr-mul2", 0] } },
			{ "patchline": { "source": ["obj-snr-vel", 0], "destination": ["obj-snr-mul2", 1] } },

			{ "patchline": { "source": ["obj-js", 4], "destination": ["obj-hat-ch-msg", 0], "comment": "hat trigger → ch env" } },
			{ "patchline": { "source": ["obj-js", 5], "destination": ["obj-hat-vel", 0], "comment": "hat vel" } },
			{ "patchline": { "source": ["obj-js", 6], "destination": ["obj-hat-sel", 0], "comment": "hat type → sel" } },
			{ "patchline": { "source": ["obj-hat-sel", 0], "destination": ["obj-hat-ch-msg", 0], "comment": "closed → short env" } },
			{ "patchline": { "source": ["obj-hat-sel", 1], "destination": ["obj-hat-oh-msg", 0], "comment": "open → long env" } },
			{ "patchline": { "source": ["obj-hat-ch-msg", 0], "destination": ["obj-hat-aenv", 0] } },
			{ "patchline": { "source": ["obj-hat-oh-msg", 0], "destination": ["obj-hat-aenv", 0] } },
			{ "patchline": { "source": ["obj-hat-noise", 0], "destination": ["obj-hat-hp", 0], "comment": "noise → HP" } },
			{ "patchline": { "source": ["obj-hat-hp", 1], "destination": ["obj-hat-mul", 1], "comment": "HP output" } },
			{ "patchline": { "source": ["obj-hat-aenv", 0], "destination": ["obj-hat-mul", 0] } },
			{ "patchline": { "source": ["obj-hat-mul", 0], "destination": ["obj-hat-mul2", 0] } },
			{ "patchline": { "source": ["obj-hat-vel", 0], "destination": ["obj-hat-mul2", 1] } },

			{ "patchline": { "source": ["obj-kick-mul2", 0], "destination": ["obj-mix1", 0], "comment": "kick → mix" } },
			{ "patchline": { "source": ["obj-snr-mul2", 0], "destination": ["obj-mix1", 1], "comment": "snare → mix" } },
			{ "patchline": { "source": ["obj-mix1", 0], "destination": ["obj-mix2", 0] } },
			{ "patchline": { "source": ["obj-hat-mul2", 0], "destination": ["obj-mix2", 1], "comment": "hat → mix" } },
			{ "patchline": { "source": ["obj-mix2", 0], "destination": ["obj-master-gain", 0] } },
			{ "patchline": { "source": ["obj-master-gain", 0], "destination": ["obj-out", 0], "comment": "L out" } },
			{ "patchline": { "source": ["obj-master-gain", 0], "destination": ["obj-out", 1], "comment": "R out (mono)" } },

			{ "patchline": { "source": ["obj-js", 7], "destination": ["obj-set-status", 0] } },
			{ "patchline": { "source": ["obj-set-status", 0], "destination": ["obj-status", 0] } }
		]
	}
}
