export function TermsPage() {
  return (
    <div className="ka-legal-page">
      <button className="ka-legal-back" onClick={() => { window.location.hash = '#/' }}>
        &larr; Back to Kernel
      </button>

      <h1>Terms of Service</h1>
      <p className="ka-legal-updated">Last updated: February 26, 2026</p>

      <p>
        By using Kernel, you agree to these terms. Kernel is operated by Isaac Hernandez.
        If you do not agree, do not use the service.
      </p>

      <h2>1. What Kernel Is</h2>

      <p>
        Kernel is a personal AI assistant available at kernel.chat. It uses large language models
        to have conversations, answer questions, help with creative and technical work, and
        build a persistent memory of your interests and goals.
      </p>

      <p>
        <strong>AI Disclosure:</strong> When you use Kernel, you are interacting with an artificial
        intelligence system, not a human. All responses are generated by AI language models. While
        Kernel maintains memory and personality across sessions, it is a software system &mdash; not
        a person. This disclosure is provided in compliance with the EU AI Act and applicable
        transparency regulations.
      </p>

      <h2>2. Your Account</h2>

      <p>
        You are responsible for your account credentials. One account per person.
        You must be at least 13 years old to use Kernel (16 in the EU/EEA).
        You are responsible for all activity that occurs under your account.
      </p>

      <h2>3. What You Own</h2>

      <p>
        You own the content you create and share through Kernel. Your messages, uploaded files,
        and creative outputs belong to you. We do not claim ownership of your content.
      </p>

      <p>
        By submitting content to Kernel, you grant us a limited, non-exclusive license to process
        that content solely for the purpose of providing and improving the service for you. This
        license terminates when you delete the content or your account.
      </p>

      <h2>4. Our Intellectual Property</h2>

      <p>
        The Kernel service, including its software, design, branding, agent architecture, and
        documentation, is owned by Isaac Hernandez. These terms do not grant you any right to use
        our trademarks, logos, or branding. You may not copy, modify, distribute, or reverse-engineer
        any part of the Kernel platform.
      </p>

      <h2>5. What We Do With Your Conversations</h2>

      <p>
        Kernel stores your conversations to provide continuity across sessions. It analyzes your
        messages to build a memory profile, knowledge graph, and multi-agent perception model
        (see our <a href="#/privacy">Privacy Policy</a> for details on the Convergence system).
        This analysis is solely to improve your experience with Kernel.
      </p>

      <p>
        We do not use your conversations to train AI models. We do not sell or share your
        conversation data.
      </p>

      <h2>6. AI-Generated Content</h2>

      <p>
        Kernel's responses are generated by AI language models. You should be aware of the
        following regarding AI-generated content:
      </p>

      <ul>
        <li>AI outputs may contain errors, inaccuracies, biases, or hallucinations</li>
        <li>AI-generated content may inadvertently reproduce or resemble third-party copyrighted material, trademarks, or other protected intellectual property</li>
        <li>We do not warrant that AI-generated content is original, accurate, or free from third-party rights</li>
        <li>You are solely responsible for reviewing, verifying, and ensuring that any AI-generated content you use complies with applicable laws and does not infringe third-party rights</li>
        <li>Do not rely on Kernel for medical, legal, financial, or other professional advice without independent verification from a qualified professional</li>
      </ul>

      <h2>7. Acceptable Use</h2>

      <p>Do not use Kernel to:</p>

      <ul>
        <li>Generate content that harms others or violates the law</li>
        <li>Attempt to extract, manipulate, or abuse the underlying AI models</li>
        <li>Circumvent rate limits or security measures</li>
        <li>Impersonate others or misrepresent your identity</li>
        <li>Use automated systems to access Kernel without permission</li>
        <li>Generate spam, malware, or content intended to deceive</li>
        <li>Engage in any activity that could damage, disable, or impair the service</li>
      </ul>

      <h2>8. Account Suspension and Termination</h2>

      <p>
        We reserve the right to suspend or terminate your account, without prior notice, if we
        reasonably believe you have violated these terms, including the acceptable use policy.
        We may also suspend accounts to protect the security or integrity of the service, or
        to comply with legal obligations.
      </p>

      <p>
        Upon termination, your right to use Kernel ceases immediately. We may, at our discretion,
        delete your account data. If you believe your account was suspended in error, contact us
        at <a href="mailto:isaacsight@gmail.com">isaacsight@gmail.com</a>.
      </p>

      <p>
        You may terminate your account at any time by deleting it through account settings.
      </p>

      <h2>9. Kernel Pro</h2>

      <p>
        Kernel Pro is a paid subscription that unlocks additional features including deep research,
        multi-agent collaboration, extended thinking, and higher usage limits. Payments are processed
        by Stripe. You can cancel at any time through your account settings or the Stripe customer
        portal. Refunds are handled on a case-by-case basis.
      </p>

      <h2>10. Free Tier Limits</h2>

      <p>
        Free accounts are limited to 20 messages per 24-hour rolling window. This limit resets
        automatically. Kernel Pro removes this limit.
      </p>

      <h2>11. Service Availability</h2>

      <p>
        We strive to keep Kernel available and reliable, but we do not guarantee uninterrupted
        or error-free service. Kernel may be temporarily unavailable due to maintenance, updates,
        third-party service disruptions, or circumstances beyond our control (including but not
        limited to natural disasters, internet outages, or infrastructure failures). We are not
        liable for any loss or damage resulting from service interruptions.
      </p>

      <h2>12. Limitation of Liability</h2>

      <p>
        We provide Kernel &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind,
        whether express or implied, including but not limited to implied warranties of merchantability,
        fitness for a particular purpose, and non-infringement.
      </p>

      <p>
        To the maximum extent permitted by applicable law, in no event shall Isaac Hernandez, Kernel,
        or any affiliated parties be liable for any indirect, incidental, special, consequential,
        or punitive damages, or any loss of profits, data, use, or goodwill, arising out of or
        related to your use of or inability to use the service.
      </p>

      <p>
        Our total aggregate liability for all claims arising out of or related to these terms or
        the service shall not exceed the greater of (a) the total amount you paid to us in the
        twelve (12) months preceding the claim, or (b) one hundred U.S. dollars ($100).
      </p>

      <p>
        This limitation applies regardless of the theory of liability (contract, tort, negligence,
        strict liability, or otherwise) and even if we have been advised of the possibility of
        such damages.
      </p>

      <h2>13. Indemnification</h2>

      <p>
        You agree to indemnify, defend, and hold harmless Isaac Hernandez and Kernel from and
        against any claims, damages, losses, liabilities, costs, and expenses (including reasonable
        attorneys&rsquo; fees) arising out of or related to:
      </p>

      <ul>
        <li>Your use of Kernel in violation of these terms</li>
        <li>Your violation of the acceptable use policy</li>
        <li>Your use or distribution of AI-generated content from Kernel</li>
        <li>Your violation of any applicable law or third-party rights</li>
        <li>Any content you submit to the service</li>
      </ul>

      <h2>14. Data Deletion</h2>

      <p>
        You can delete your conversations, memory, knowledge graph, goals, or your entire account
        at any time through account settings. Deletion is permanent and cannot be undone.
      </p>

      <h2>15. Changes to These Terms</h2>

      <p>
        We may update these terms as Kernel evolves. When we make material changes, we will notify
        you through the app or by email at least thirty (30) days before the changes take effect.
        If you do not agree with the revised terms, you may delete your account before the changes
        become effective. Continued use of Kernel after the effective date constitutes acceptance
        of the updated terms.
      </p>

      <h2>16. Governing Law</h2>

      <p>
        These terms are governed by and construed in accordance with the laws of the State of
        California, United States, without regard to its conflict of law provisions. Any legal
        proceedings arising out of or related to these terms or the service shall be brought
        exclusively in the state or federal courts located in Los Angeles County, California,
        and you consent to the personal jurisdiction of such courts.
      </p>

      <h2>17. Dispute Resolution</h2>

      <p>
        <strong>Informal Resolution First:</strong> Before initiating any formal proceeding, you
        agree to contact us at <a href="mailto:isaacsight@gmail.com">isaacsight@gmail.com</a> and
        attempt to resolve the dispute informally for at least thirty (30) days.
      </p>

      <p>
        <strong>Binding Arbitration:</strong> If we cannot resolve the dispute informally, any
        dispute, claim, or controversy arising out of or relating to these terms or the service
        shall be resolved by binding arbitration administered under the rules of the American
        Arbitration Association (AAA). The arbitration shall be conducted in Los Angeles County,
        California, or at a mutually agreed location. The arbitrator&rsquo;s decision shall be
        final and binding.
      </p>

      <p>
        <strong>Class Action Waiver:</strong> You agree that any dispute resolution proceedings
        will be conducted only on an individual basis, not as a class, consolidated, or
        representative action. You waive any right to participate in a class action lawsuit
        or class-wide arbitration against Kernel or Isaac Hernandez.
      </p>

      <p>
        <strong>Exceptions:</strong> Either party may seek injunctive or other equitable relief
        in any court of competent jurisdiction for claims involving intellectual property
        infringement or unauthorized access to the service.
      </p>

      <h2>18. Severability</h2>

      <p>
        If any provision of these terms is found to be unenforceable or invalid by a court of
        competent jurisdiction, that provision shall be enforced to the maximum extent permissible,
        and the remaining provisions shall remain in full force and effect.
      </p>

      <h2>19. Entire Agreement</h2>

      <p>
        These terms, together with the <a href="#/privacy">Privacy Policy</a>, constitute the
        entire agreement between you and Isaac Hernandez regarding your use of Kernel. These
        terms supersede any prior agreements or understandings, whether written or oral, relating
        to the service.
      </p>

      <h2>20. Contact</h2>

      <p>
        Questions: <a href="mailto:isaacsight@gmail.com">isaacsight@gmail.com</a>
      </p>
    </div>
  )
}
