export function TermsPage() {
  return (
    <div className="ka-legal-page">
      <button className="ka-legal-back" onClick={() => { window.location.hash = '#/' }}>
        &larr; Back to Kernel
      </button>

      <h1>Terms of Service</h1>
      <p className="ka-legal-updated">Last updated: February 24, 2026</p>

      <p>
        By using Kernel, you agree to these terms. Kernel is operated by Isaac Hernandez.
        If you do not agree, do not use the service.
      </p>

      <h2>1. What Kernel Is</h2>

      <p>
        Kernel is a personal AI assistant available at kernel.chat. It uses large language models
        to have conversations, answer questions, help with creative and technical work, and
        build a persistent memory of your interests and goals.
      </p>

      <h2>2. Your Account</h2>

      <p>
        You are responsible for your account credentials. One account per person.
        You must be at least 13 years old to use Kernel.
      </p>

      <h2>3. What You Own</h2>

      <p>
        You own the content you create and share through Kernel. Your messages, uploaded files,
        and creative outputs belong to you. We do not claim ownership of your content.
      </p>

      <h2>4. What We Do With Your Conversations</h2>

      <p>
        Kernel stores your conversations to provide continuity across sessions. It analyzes your
        messages to build a memory profile, knowledge graph, and multi-agent perception model
        (see our <a href="#/privacy">Privacy Policy</a> for details on the Convergence system).
        This analysis is solely to improve your experience with Kernel.
      </p>

      <p>
        We do not use your conversations to train AI models. We do not sell or share your
        conversation data.
      </p>

      <h2>5. Acceptable Use</h2>

      <p>Do not use Kernel to:</p>

      <ul>
        <li>Generate content that harms others or violates the law</li>
        <li>Attempt to extract, manipulate, or abuse the underlying AI models</li>
        <li>Circumvent rate limits or security measures</li>
        <li>Impersonate others or misrepresent your identity</li>
        <li>Use automated systems to access Kernel without permission</li>
      </ul>

      <h2>6. Kernel Pro</h2>

      <p>
        Kernel Pro is a paid subscription that unlocks additional features including deep research,
        multi-agent collaboration, and higher usage limits. Payments are processed by Stripe.
        You can cancel at any time through your account settings or the Stripe customer portal.
        Refunds are handled on a case-by-case basis.
      </p>

      <h2>7. Limitations</h2>

      <p>
        Kernel is an AI. It can be wrong. Do not rely on Kernel for medical, legal, or financial
        advice without independent verification. Kernel's responses are generated by language
        models and may contain errors, biases, or hallucinations.
      </p>

      <p>
        We provide Kernel "as is" without warranties. We are not liable for decisions you make
        based on Kernel's responses.
      </p>

      <h2>8. Free Tier Limits</h2>

      <p>
        Free accounts are limited to 20 messages per 24-hour rolling window. This limit resets
        automatically. Kernel Pro removes this limit.
      </p>

      <h2>9. Data Deletion</h2>

      <p>
        You can delete your conversations, memory, knowledge graph, goals, or your entire account
        at any time through account settings. Deletion is permanent and cannot be undone.
      </p>

      <h2>10. Changes</h2>

      <p>
        We may update these terms as Kernel evolves. Continued use after changes constitutes
        acceptance.
      </p>

      <h2>11. Contact</h2>

      <p>
        Questions: <a href="mailto:isaacsight@gmail.com">isaacsight@gmail.com</a>
      </p>
    </div>
  )
}
