
FROM node:18-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY . .
RUN pnpm install

# Just run the debugger dev server by default for local iteration via docker
CMD ["pnpm", "dev"]
