"""
Systemmonitor - Monitors system health and resource usage
Autogenerated by Toolsmith
"""

import logging

logger = logging.getLogger("Systemmonitor")

class Systemmonitor:
    """
    Monitors system health and resource usage.
    """
    def __init__(self):
        self.name = "Systemmonitor"
        self.role = "Monitors system health and resource usage"
        
    def execute(self):
        import shutil
        import psutil
        import socket
        
        report = {}
        
        # 1. Disk Usage
        total, used, free = shutil.disk_usage("/")
        report['disk_free_gb'] = free // (2**30)
        report['disk_percent'] = (used / total) * 100
        
        # 2. Memory
        mem = psutil.virtual_memory()
        report['ram_percent'] = mem.percent
        
        # 3. Process
        report['cpu_percent'] = psutil.cpu_percent(interval=1)
        
        # 4. Check Ports (Studio OS default 8000, 3000)
        ports = [8000, 3000, 5173]
        open_ports = []
        for port in ports:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            result = sock.connect_ex(('127.0.0.1', port))
            if result == 0:
                open_ports.append(port)
            sock.close()
        report['active_ports'] = open_ports
        
        logger.info(f"System Monitor Report: {report}")
        print(f"🖥️ SYSTEM STATUS:\n- CPU: {report['cpu_percent']}%\n- RAM: {report['ram_percent']}%\n- Disk Free: {report['disk_free_gb']} GB\n- Active Ports: {open_ports}")
        
        return True

if __name__ == "__main__":
    agent = Systemmonitor()
    agent.execute()
