"""
Toolsmith - The Agent Builder
Responsible for scaffolding, registering, and managing other AI agents/tools.
"""

import os
import inspect
import logging

logger = logging.getLogger("Toolsmith")

class Toolsmith:
    def __init__(self):
        self.engineers_dir = os.path.dirname(__file__)
        self.init_path = os.path.join(self.engineers_dir, "__init__.py")
        
    def scaffold_tool(self, name: str, role: str = "Assistant"):
        """
        Creates a new engineer Python file with a standard class template.
        Validates that the file doesn't already exist.
        """
        class_name = self._to_class_name(name)
        file_name = self._to_snake_case(name) + ".py"
        file_path = os.path.join(self.engineers_dir, file_name)
        
        if os.path.exists(file_path):
            logger.warning(f"Tool {name} already exists at {file_path}")
            return False, f"File {file_name} already exists."
            
        template = f"""\"\"\"
{class_name} - {role}
Autogenerated by Toolsmith
\"\"\"

import logging

logger = logging.getLogger("{class_name}")

class {class_name}:
    \"\"\"
    {role}.
    \"\"\"
    def __init__(self):
        self.name = "{class_name}"
        self.role = "{role}"
        
    def execute(self):
        logger.info(f"{{self.name}} is executing.")
        # Add logic here
        return True

if __name__ == "__main__":
    agent = {class_name}()
    agent.execute()
"""
        try:
            with open(file_path, "w") as f:
                f.write(template)
            logger.info(f"Scaffolded {class_name} at {file_path}")
            return True, file_path
        except Exception as e:
            logger.error(f"Failed to scaffold: {e}")
            return False, str(e)

    def register_tool(self, name: str):
        """
        Adds the new tool to __init__.py so it can be imported.
        """
        class_name = self._to_class_name(name)
        module_name = self._to_snake_case(name)
        
        try:
            with open(self.init_path, "r") as f:
                lines = f.readlines()
                
            # Check if already registered
            if any(f"from .{module_name} import {class_name}" in line for line in lines):
                return True, "Already registered."
                
            # Find the __all__ block
            all_start_index = -1
            imports_end_index = -1
            
            for i, line in enumerate(lines):
                if line.strip().startswith("__all__ = ["):
                    all_start_index = i
                if line.strip().startswith("from .") or line.strip().startswith("import "):
                    imports_end_index = i
            
            # Insert import statement after the last import
            insertion_point = imports_end_index + 1 if imports_end_index > 0 else 0
            lines.insert(insertion_point, f"from .{module_name} import {class_name}\n")
            
            # Add to __all__
            # We search for the closing bracket ']' of __all__
            all_end_index = -1
            for i in range(all_start_index, len(lines)):
                if "]" in lines[i]:
                    all_end_index = i
                    break
                    
            if all_end_index != -1:
                # Insert before the closing bracket
                lines.insert(all_end_index, f"    '{class_name}',\n")
            
            with open(self.init_path, "w") as f:
                f.writelines(lines)
                
            logger.info(f"Registered {class_name} in __init__.py")
            return True, "Registered successfully."
            
        except Exception as e:
            logger.error(f"Failed to register: {e}")
            return False, str(e)
            
    def _to_class_name(self, name: str) -> str:
        # snake_case or space separated to PascalCase
        parts = name.replace("_", " ").split()
        return "".join(p.capitalize() for p in parts)
        
    def _to_snake_case(self, name: str) -> str:
        # PascalCase or Space Separated to snake_case
        import re
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower().replace(" ", "_")

if __name__ == "__main__":
    ts = Toolsmith()
    print("Toolsmith Ready.")
