// Attestation discipline.
//
// When an agent signs, sends, or confirms on a principal's behalf, the
// substrate records who actually composed the content the agent attested
// to. Downstream evaluators (auditors, recipients, regulators) need to be
// able to distinguish "this content was authored by the principal" from
// "this content was generated by an agent on the principal's authorization
// but not authored by the principal."
//
// The attestation record is a deterministic structure, content-addressed
// via SHA-256 over its canonical JSON form. The substrate writes it to the
// audit log alongside the action it attests to, so retrospective review
// can trace any consequential output back to its authorship state.

import { createHash } from 'node:crypto'

export type AuthorshipState =
  | 'principal-authored'           // principal wrote the content themselves
  | 'principal-refined-from-agent' // agent produced a draft, principal substantively rewrote
  | 'agent-drafted'                // agent generated the content, principal reviewed without rewriting
  | 'agent-fully-autonomous'       // agent generated and sent without principal review
  | 'unknown'                      // state not tracked

export interface AttestationRecord {
  /** Schema version — bump when fields change incompatibly. */
  v: 1
  /** ISO 8601 timestamp when the attestation was created. */
  ts: string
  /** Free-form identifier for the principal (e.g. email). */
  principalId: string
  /** Free-form identifier for the agent that produced the content (e.g. 'kbot-orchestrator@0.3.0-alpha.0'). */
  agentId: string
  /** State of authorship for the content being attested. */
  authorship: AuthorshipState
  /** SHA-256 hash of the attested content (typically the final body that ships). */
  contentHash: string
  /** Optional: SHA-256 hash of the agent's pre-refinement draft, if applicable. */
  agentDraftHash?: string
  /** What the principal is attesting (e.g., "the content above is accurate to my knowledge"). */
  attestation: string
  /** Free-form context the substrate would need to replay the decision. */
  context?: Record<string, unknown>
}

export interface AttestationBuilder {
  principalId: string
  agentId: string
  authorship: AuthorshipState
  content: string
  agentDraft?: string
  attestation: string
  context?: Record<string, unknown>
}

/** Compute a stable SHA-256 hash of a string. */
export function sha256Hex(input: string): string {
  return createHash('sha256').update(input).digest('hex')
}

/** Create an attestation record with stable, content-addressed hashing. */
export function createAttestation(b: AttestationBuilder): AttestationRecord {
  const record: AttestationRecord = {
    v: 1,
    ts: new Date().toISOString(),
    principalId: b.principalId,
    agentId: b.agentId,
    authorship: b.authorship,
    contentHash: sha256Hex(b.content),
    attestation: b.attestation,
  }
  if (b.agentDraft) record.agentDraftHash = sha256Hex(b.agentDraft)
  if (b.context) record.context = b.context
  return record
}

/** Canonical JSON serialization (stable key ordering) — content-addressable. */
export function canonicalize(record: AttestationRecord): string {
  const ordered: Record<string, unknown> = {}
  const keys = Object.keys(record).sort() as (keyof AttestationRecord)[]
  for (const k of keys) {
    const value = record[k]
    if (value !== undefined) ordered[k] = value
  }
  return JSON.stringify(ordered)
}

/** Content-address the attestation itself (SHA-256 of its canonical form). */
export function recordHash(record: AttestationRecord): string {
  return sha256Hex(canonicalize(record))
}

/** A simple verifier: given a record + the content, confirm the content hash matches what was attested. */
export function verifyAttestation(record: AttestationRecord, content: string): { ok: boolean; reason?: string } {
  const expected = sha256Hex(content)
  if (record.contentHash !== expected) {
    return {
      ok: false,
      reason: `content hash mismatch: attestation records ${record.contentHash}, content hashes to ${expected}`,
    }
  }
  return { ok: true }
}
