#!/usr/bin/env python3
"""
Generate Revenue Report Script

Scans the studio's content and outputs to generate a
monetization strategy document.
"""

import os
import sys
import json
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from admin.engineers.revenue_agent import get_revenue_agent
from config import config


def main():
    print("=== Studio OS Revenue Report Generator ===\n")
    
    agent = get_revenue_agent()
    
    # Define directories to scan for monetizable assets
    scan_dirs = [
        config.CONTENT_DIR,  # Blog posts
        os.path.join(config.BASE_DIR, "admin", "brain", "agents"),  # Agent configs
    ]
    
    all_assessments = []
    all_offerings = []
    
    for scan_dir in scan_dirs:
        if not os.path.exists(scan_dir):
            print(f"Skipping (not found): {scan_dir}")
            continue
            
        print(f"Scanning: {scan_dir}")
        
        for filename in os.listdir(scan_dir):
            if not filename.endswith(".md"):
                continue
                
            filepath = os.path.join(scan_dir, filename)
            
            # Skip very small files
            if os.path.getsize(filepath) < 500:
                continue
                
            assessment = agent.assess_monetization_readiness(filepath)
            all_assessments.append(assessment)
            
            # Only generate offerings for high-potential assets
            if assessment.get("score", 0) >= 6.0:
                offering = agent.generate_offering(filepath)
                all_offerings.append(offering)
    
    # Generate the summary
    summary = agent.get_revenue_summary()
    
    # Build the report
    report_lines = [
        "# Studio OS Revenue Strategy",
        f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
        "## Executive Summary",
        "",
        f"- **Total Artifacts Assessed**: {summary['total_assessed_artifacts']}",
        f"- **Average Monetization Score**: {summary['average_score']:.1f}/10",
        f"- **Total Offerings Generated**: {summary['total_offerings']}",
        f"- **Total Revenue (to date)**: ${summary['total_revenue_usd']:.2f}",
        "",
        "---",
        "",
        "## High-Potential Offerings",
        ""
    ]
    
    # Sort offerings by suggested price
    sorted_offerings = sorted(all_offerings, key=lambda x: x.get("suggested_price_usd", 0), reverse=True)
    
    for i, offering in enumerate(sorted_offerings[:10], 1):  # Top 10
        report_lines.append(f"### {i}. {offering.get('title', 'Untitled')}")
        report_lines.append(f"- **Type**: {offering.get('type', 'N/A')}")
        report_lines.append(f"- **Suggested Price**: ${offering.get('suggested_price_usd', 0)}")
        report_lines.append(f"- **Assessment Score**: {offering.get('assessment_score', 0)}/10")
        report_lines.append(f"- **Description**: {offering.get('description', '')}")
        report_lines.append("")
    
    report_lines.extend([
        "---",
        "",
        "## Recommendations",
        "",
        "1. **Prioritize Consulting Packages**: High-score assets should be bundled into consulting offerings.",
        "2. **Create Productized Downloads**: Mid-tier assets (6-7 score) are ideal for Gumroad-style digital products.",
        "3. **Build a Funnel**: Use low-score content as free lead magnets to drive traffic to paid offerings.",
        "",
        "---",
        "",
        "*Report generated by RevenueAgent.*"
    ])
    
    report_content = "\n".join(report_lines)
    
    # Save the report
    output_path = os.path.join(config.BASE_DIR, "admin", "brain", "REVENUE_STRATEGY.md")
    with open(output_path, "w") as f:
        f.write(report_content)
    
    print(f"\n✅ Revenue Strategy Report saved to: {output_path}")
    print(f"\n--- Summary ---")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
